CREATE EXTENSION IF NOT EXISTS pg_trgm
WITH SCHEMA public;


CREATE SCHEMA IF NOT EXISTS dms;
CREATE SCHEMA IF NOT EXISTS portal;

\getenv dms_password DMS_DB_PASSWORD
\getenv portal_password PORTAL_DB_PASSWORD

CREATE USER dms_app WITH PASSWORD :'dms_password';
CREATE USER portal_app WITH PASSWORD :'portal_password';


GRANT USAGE, CREATE ON SCHEMA dms TO dms_app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA dms TO dms_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA dms
    GRANT ALL PRIVILEGES ON TABLES TO dms_app;


GRANT USAGE, CREATE ON SCHEMA portal TO portal_app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA portal TO portal_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA portal
    GRANT ALL PRIVILEGES ON TABLES TO portal_app;